### ISSUE TITLE
[REQ] Set the license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [victormassatieze/phase_reconstruction#1]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project](https://github.com/forart/HyMPS) (under the [Tools section](https://github.com/forart/HyMPS/blob/main/A_Tools.md)), can you please set licensing terms for this git ?

Our "problem" is that does not generates a correct badge: 

![](https://flat.badgen.net/github/license/victormassatieze/phase_reconstruction/?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/victormassatieze/phase_reconstruction/?label=LICENSE)

Thanks in advance.

**Comment by victormassatieze** [comment]
Hello! Sorry for the delay. If you still want to use the code, I added the MIT license to this repository.
